# Generated by Django 4.1.7 on 2023-03-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Following Link'},
        ),
    ]
