# Generated by Django 4.1.7 on 2023-03-27 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_moderator',
            field=models.ForeignKey(help_text='Link to the :model:`pulsifi.user` object instance (from the set of moderators) that has been assigned to moderate this report.', limit_choices_to={'groups__name': 'Moderators', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_assigned_report_set', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Moderator'),
        ),
    ]
