# Generated by Django 4.1.7 on 2023-03-21 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0002_alter_follow_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_once',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_follow_self',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'followed'), name='follow_once'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', models.F('followed')), _negated=True), name='not_follow_self'),
        ),
    ]
