# Generated by Django 4.1.7 on 2023-03-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pulsifi', '0003_rename_visible_pulse_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='_content_type',
            field=models.ForeignKey(help_text='Link to the content type of the replied_content instance (either :model:`pulsifi.pulse` or :model:`pulsifi.reply`).', limit_choices_to={'app_label': 'pulsifi', 'model__in': {'pulse', 'reply'}}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Replied Content Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='_content_type',
            field=models.ForeignKey(help_text='Link to the content type of the reported_object instance (either :model:`pulsifi.user`, :model:`pulsifi.pulse` or :model:`pulsifi.reply`).', limit_choices_to={'app_label': 'pulsifi', 'model__in': {'user', 'pulse', 'reply'}}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Reported Object Type'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', '_object_id', '_content_type')},
        ),
    ]
