# Generated by Django 4.1.7 on 2023-04-03 02:10

import django.core.validators
from django.db import migrations, models

import pulsifi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0004_alter_reply__content_type_alter_report__content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, error_messages={'null': 'Bio field cannot be null, use an empty string instead.'}, help_text='Longer textfield containing an autobiographical description of this user.', max_length=200, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email Address is a required field.', 'null': 'Email Address is a required field.', 'unique': 'That Email Address is already in use by another user.'}, max_length=254, unique=True, validators=[pulsifi.validators.HTML5EmailValidator(), pulsifi.validators.FreeEmailValidator(), pulsifi.validators.ConfusableEmailValidator(), pulsifi.validators.PreexistingEmailTLDValidator(), pulsifi.validators.ExampleEmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username is a required field.', 'null': 'Username is a required field.', 'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w._]+\\Z', "Enter a valid username. It must contain only letters, digits, '.' and '_'characters."), pulsifi.validators.ReservedUsernameValidator(), pulsifi.validators.ConfusableUsernameValidator(), django.core.validators.MinLengthValidator(4, 'Username must have at least 4 characters.')], verbose_name='Username'),
        ),
    ]
