# Generated by Django 4.2 on 2023-04-28 18:06

import django.core.validators
from django.db import migrations, models

import pulsifi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0005_alter_user_bio_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username is a required field.', 'null': 'Username is a required field.', 'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('\\A(?!.*[._]{3})(?=\\A\\p{L}.*\\p{L}.*\\Z)[\\p{L}._]+\\Z', "Enter a valid username. It must contain only letters, digits, '.' and '_'characters."), pulsifi.validators.ReservedUsernameValidator(), pulsifi.validators.ConfusableUsernameValidator(), django.core.validators.MinLengthValidator(4, 'Username must have at least 4 characters.')], verbose_name='Username'),
        ),
    ]
